module.exports = {
  extends: ['airbnb', 'prettier'],
  parser: 'babel-eslint',
  rules: {
    'no-nested-ternary': 0,
    'no-param-reassign': 0,
    'no-plusplus': 0,
    'no-shadow': 0,
    'no-return-assign': [2, 'except-parens'],
    'no-use-before-define': [2, {variables: false}],
    'spaced-comment': 0,
    'global-require': 0,
    'import/first': 0,
    'import/extensions': 0,
    'import/no-unresolved': [2, {ignore: ['^wedding/']}],
    'import/prefer-default-export': 0,
    'jsx-a11y/anchor-is-valid': 0,
    'jsx-a11y/media-has-caption': 0,
    'react/forbid-prop-types': 0,
    'react/jsx-one-expression-per-line': 0,
    'react/jsx-closing-tag-location': 0,
    'react/jsx-filename-extension': 0,
    'react/require-default-props': 0,
    'react/react-in-jsx-scope': 0,
    'react/no-array-index-key': 0,
    'react/no-multi-comp': 0,
    'react/sort-comp': 0,
  },
};
